#!/usr/bin/env ruby
# Usage: cfop ccdb-console [path_to_state_yml]
# Summary: Use credentials from state.yml and open a mysql session against CCDB.
# Help: Not every copy of state.yml has these credentials.
# If you can't use this file, you might be on a machine that is not intended
# to connect to CCDB.

require "#{ENV["_CFOP_ROOT"]}/share/put_cfop_on_load_path"
require "cfop/bosh_state"
require "tempfile"

abort "Incorrect number of arguments" if ARGV.size > 1

bosh_state_path = ARGV.fetch(0, CfOp::BoshState.default_path)
puts "Using config file: #{bosh_state_path}"

bosh_state = CfOp::BoshState.from_file(bosh_state_path)
password = bosh_state.ccdb_password

Tempfile.open(['my', '.cnf']) do |f|
  f.write(<<-MYSQL)
[client]
password=#{password}
MYSQL
  f.flush

  mysql_conf_path = f.path
  command = bosh_state.ccdb_command(mysql_conf_path)
  mysqld_path = "/var/vcap/packages/mysqlclient"

  Process.waitpid(Process.spawn(PATH: "$PATH:#{mysqld_path}/bin", LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:#{mysqld_path}/lib/mysql",command))
end
