#!/usr/bin/env ruby
# Usage: cfop warden-handle app_name_or_guid [path_to_instances_json]
# Summary: Get the warden handle(s) that correspond with the given app name or guid.

require "#{ENV["_CFOP_ROOT"]}/share/put_cfop_on_load_path"
require "cfop/instance_snapshot"

abort "Argument mismatch" if ARGV.size < 1 || ARGV.size > 2

snapshot_path = ARGV.size == 2 ? ARGV[1] : CfOp::InstanceSnapshot.default_path
puts "Using instance snapshot: #{snapshot_path}"

snapshot = CfOp::InstanceSnapshot.from_file(snapshot_path)
handles = snapshot.warden_handles_by_app_guid(ARGV[0]).concat(
            snapshot.warden_handles_by_app_name(ARGV[0])
          )

handles.each do |handle|
  puts handle
end

abort "No handles found with name or guid: #{ARGV[0]}" if handles.empty?
